### ISSUE TITLE
Problem with <Node p>.text?

### ISSUE THREAD

**Issue by Mancuerna** [rushter/selectolax#1]
I am porting some code from `beautifulsoup4` to `selectolax` and I am having some troubles trying to get the text content from a `p` element.

The HTML is as follow:
`<div class="post-contents">
                        <p><a href="/testtest" rel="5" class="quote">#5</a> <a href="testtest" rel="2" class="quote">#2</a> <a href="testtest rel="4" class="quote">#4</a> testtesttesttesttest.</p>                    </div>`

I am using this selector `div.post-contents p` to get the `p` elements and then `.text` is used over each node, getting the first `#5` inside de first `a` instead of all the text inside de `p` element. Am I doing something wrong or this is the expected behaviour of `.text`?

**Comment by rushter** [comment]
It's a bug on my side. I will fix it.

**Comment by rushter** [comment]
@Mancuerna You can try now, but you need to install selectolax from GitHub. 

I will add some flexibility to the text functionality before releasing it to PyPi.

**Comment by Mancuerna** [comment]
I'm having the same problem with the latest fix. Here you have a Pastebin with the code I'm using to test it (sorry for not writing it here but Github's parser is messing it up).

https://pastebin.com/BB2KK6T3

As you can see the `beautifulsoup4` print is the proper one while `selectolax` is only printing the text of the first element inside the `div`.

**Comment by rushter** [comment]
Your second example is a bit different, that's why I wanted to add additional functionality. 

```
In [1]: from selectolax.parser import HTMLParser

In [2]: html = '<div class="post-contents"> <p><a href="/testtest" rel="5" class="quote">#5</a> <a href="testtest" rel="2" class="quote">#2</a> <a href="testtest rel="4" class="qu
   ...: ote">#4</a> testtesttesttesttest.</p> </div>'
   ...: selector = "div.post-contents p"
   ...:

In [3]: for node in HTMLParser(html).css(selector):
   ...:     print(node.text(deep=False))
   ...:
   testtesttesttesttest.

In [4]: html = '<div class="post-contents"><p><strong><em>Night School Studio</em></strong>, estudio responsable de ' \
   ...:        '<em>Oxenfree</em> (una de las sorpresas del año pasado que pasó desapercibida tanto para prensa como ' \
   ...:        'comunidad), ha anunciado su próximo título, <strong><em>Afterparty</em></strong>.</p></div> '

In [5]:

In [5]: for node in HTMLParser(html).css("div.post-contents"):
   ...:     print(node.text())
   ...:
Night School Studio, estudio responsable de Oxenfree (una de las sorpresas del año pasado que pasó desapercibida tanto para prensa como comunidad), ha anunciado su próximo título, Afterparty.
```
I changed the behavior of text, now it's a function, not an attribute.
So, for the first example you need to use deep=False, otherwise, it will include all text from `a` tags. 
Can you try now? Works for me.

**Comment by Mancuerna** [comment]
It works like a charm now. Thank you for your time <3
