### ISSUE TITLE
Awful text parsing issue

### ISSUE THREAD

**Issue by mhillebrand** [rushter/selectolax#101]
When parsing the pairs of `<p>` and `<div>` tags below, something odd happens. The first `<div>`'s text erroneously contains the text for all subsequent `<div>` tags.

```python
from selectolax.parser import HTMLParser

html = """
<html>
   <body>
      <div class="List">
         <p>3</p>
         <div>tablespoons butter</div>

         <p>1</p>
         <div>cup chopped onion</div>

         <p>6</p>
         <div>large fresh thyme sprigs</div>

         <p>1</p>
         <div>large garlic clove, chopped</div>

         <p>2</p>
         <div>1-pound bags peeled baby carrots</div>

         <p>2</p>
         <div>cups low-salt chicken broth</div>
      </div>
   </body>
</html>
"""

lax = HTMLParser(html)

ingredients = lax.css_first('div.List')

amount_nodes = ingredients.css('p')
amounts = [ing.text() for ing in amount_nodes]

name_nodes = ingredients.css('div')
names = [ing.text() for ing in name_nodes]

print(names[0])
```

Here's what `names` looks like:

<img width="1432" alt="image" src="https://github.com/rushter/selectolax/assets/286198/7a49e42b-282f-44c9-8948-067f53bb005c">

However, if I change my parsing logic to the following, everything works as expected:

```python
amount_nodes = lax.css('div.List p')
amounts = [ing.text() for ing in amount_nodes]

name_nodes = lax.css('div.List div')
names = [ing.text() for ing in name_nodes]
```

Thoughts?

**Comment by rushter** [comment]
The css selector starts from the current node, you are basically selecting the main div again.

**Comment by rushter** [comment]
Because that’s how CSS selectors work, you ask for any P tags that are on
any level. When you select div, the first match is on the current level, so
any elements inside it are ignored and not selected.

**Comment by rushter** [comment]
It's supported. The way it works is it includes the current node when executing the css selector. You start at `<div class=List>`
