### ISSUE TITLE
css_matches of LexborHTMLParser does not free memory

### ISSUE THREAD

**Issue by SkySandy** [rushter/selectolax#107]
For the first time I started using the function css_matches of LexborHTMLParser in my project. And after launching the project, two hours later my computer (64GB of RAM) ran out of memory!

Python version 3.11.6 Windows 10
`
Even minimal code takes up all the memory on my computer (from your tests)

html = "<div></div><div></div><div></div>"
temp = LexborHTMLParser(html)
for i in range(1000000000):
    temp.css_matches('div')
`
With another parser in your package selectolax (Modest) is fine

**Comment by rushter** [comment]
Thanks, that should be fixed now. The new release will be automatically deployed in ~2 hours.

**Comment by SkySandy** [comment]
Thank you!

Small mistake ... CHANGES.rst shows new version 0.3.15 but should be 0.3.18.
