### ISSUE TITLE
Selectolax couldn't load large html string (87MB) but lxml could

### ISSUE THREAD

**Issue by bengabp** [rushter/selectolax#109]
In my scraper, i am dealing with large html strings and now i have run into an issue with selectolax not able to load my html string which is about 87 mb in size. I tried using lxml and it was able to load it in about 2 seconds. 

![image](https://github.com/rushter/selectolax/assets/84660669/114d4570-b081-4734-8b8d-08f751b1f010)
![image](https://github.com/rushter/selectolax/assets/84660669/3ca93bc8-af0f-4050-9f6f-b47955d33ea0)

**Comment by rushter** [comment]
That limit is artificial; I've increased it. Some people tried to load 5000 MB of binary data by accident and complained about it in the past.

**Comment by rushter** [comment]
The most recent version can now accept up to 2.4GB of HTML. It will be on pypi in a few hours.

**Comment by bengabp** [comment]
I am still getting this error even with the update
![image](https://github.com/rushter/selectolax/assets/84660669/0036e43d-6831-4cbe-9ed1-d07d9446c7d0)
![image](https://github.com/rushter/selectolax/assets/84660669/fe46e8c2-0ae4-4a8d-a9af-51c61789dcea)
