### ISSUE TITLE
Installation fails on Korean Windows

### ISSUE THREAD

**Issue by taeminlee** [rushter/selectolax#11]
Thank you for providing a good library!

In case of Korean Windows, python use the cp949 encoding when reading the file with open function, (because of past issues related to Korean encoding).

Therefore, installing the current distribution package using pip will be aborted with the following message.

```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      Install-quywlvnk \ selectolax \ setup.py ", line 11, in <module> C: \ Users \ persu \ AppData \ Local \ Temp \
        readme = readme_file.read ()
    UnicodeDecodeError: 'cp949' codec can not decode byte 0xe2 in position 2122: illegal multibyte sequence
```

To install a package, need to assign the encoding on line 10 of setup.py as below.

`with open ('README.rst', encoding = 'utf-8') as readme_file:`

Could I ask you to reflect this part? :)

**Comment by rushter** [comment]
Thank you for your report. I've updated the setup script.
