### ISSUE TITLE
I am still getting this error even with the update - not able to load large html contents

### ISSUE THREAD

**Issue by bengabp** [rushter/selectolax#110]
I am still getting this error even with the update
![image](https://github.com/rushter/selectolax/assets/84660669/0036e43d-6831-4cbe-9ed1-d07d9446c7d0)
![image](https://github.com/rushter/selectolax/assets/84660669/fe46e8c2-0ae4-4a8d-a9af-51c61789dcea)

_Originally posted by @bengabp in https://github.com/rushter/selectolax/issues/109#issuecomment-1916832981_

**Comment by rushter** [comment]
Should be fixed in 0.3.20
