### ISSUE TITLE
Content of scripts always being outputed with .text()

### ISSUE THREAD

**Issue by LeDilam** [rushter/selectolax#115]
Why are script not ignored by the `.text()` ?
I don't understand this behavior. The content of script is not a part of the text of a web page.
Contrary to scripts, comments are ignored. And it's not like if comments were not recognized as node by selectolax, they are.

By default, we should not get script as part of the text of a webpage. It's not what the name "text" suggest.

Maybe some people want to print invisible things like scipts. It's not my case, but if some people really want, it could be an option (which should not be the default). If this option exist, maybe comment could be included with script (I will not debate about this as I don't know use-case of mixing page text with other things).

Here is a code example :
```py
from selectolax.parser import HTMLParser

html = '''<!DOCTYPE html>
<head>
	<title>Simple Example</title>
</head>
<body>
	<!-- A comment, to not output -->
	<div>
		<p>Paragraph 1 <a>with a link</a> in it.</p>
		<p>Paragraph 2. It continue a little.</p>
	</div>
	<script>
		// Javascript needs to be removed from the outputed text
		let my_javascript;
	</script>
</body>
'''

tree = HTMLParser(html)

print (tree.body.text(separator=" ", strip=True))
```
It give :
```
   Paragraph 1 with a link in it.  Paragraph 2. It continue a little.   // Javascript needs to be removed from the outputed text
                let my_javascript;
```

It's the case both for `.text()` of both selectolax.parser and selectolax.lexbor, and for `.text_lexbor()` from selectolax.lexbor.

**Comment by rushter** [comment]
Please use `strip_tags`. The content inside the scripts is also text, which can be misleading for some people, so yeah, we need to update the docs.

```
>>> tree = HTMLParser('<html><head></head><body><script></script><div>Hello world!</div></body></html>')
>>> tags = ['head', 'style', 'script', 'xmp', 'iframe', 'noembed', 'noframes']
>>> tree.strip_tags(tags)
>>> tree.html
'<html><body><div>Hello world!</div></body></html>'```

It's considered text according to the DOM model or HTML specs.
You can test it in the browsers. Selectolax works similar to browsers.

````
document.querySelectorAll("script")[1].textContent
document.querySelectorAll("script")[1].textContent
`\n(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','GTM-KTCFC3S');\n\nvar subjectFolder = location.pathname;\nsubjectFolder = subjectFolder.replace("/", "");\nif (subjectFolder.startsWith("python/") == true ) {\n  if (subjectFolder.includes("/numpy/") == true ) {\n    subjectFolder = "numpy/"\n  } else if (subjectFolder.includes("/pandas/") == true ) {\n      subjectFolder = "pandas/"\n  } else if (subjectFolder.includes("/scipy/") == true ) {\n      subjectFolder = "scipy/"\n  }\n}\nsubjectFolder = subjectFolder.substr(0, subjectFolder.indexOf("/"));\n`
```
