### ISSUE TITLE
Add pyinstaller hooks?

### ISSUE THREAD

**Issue by baseplate-admin** [rushter/selectolax#122]
Hi, it seems that `selectolax` doesn't work with `pyinstaller` due to it's Cython codes.

Projects that use hybrid ( python + other language ) approach has to include [hooks](https://pyinstaller.org/en/stable/hooks.html) to allow the projects to be built properly.

For example
- [numpy](https://github.com/numpy/numpy/tree/8a7e0e059db8ea2ac0997c73e32eebb72e54b5b9/numpy/_pyinstaller)

If i somehow add `selectolax`  into `hidden_import`, i get this error
```
PyInstaller\hooks\rthooks\pyi_rth_pkgres.py:36: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "cli.py", line 2, in <module>
  File "builder\staff.py", line 2, in <module>
  File "selectolax\__init__.py", line 10, in <module>
ImportError: cannot import name 'modest' from partially initialized module 'selectolax' (most likely due to a circular import) (C:\Users\baseplate-admin\AppData\Local\Temp\_MEI235082\selectolax\__init__.pyc)
[30172] Failed to execute script 'cli' due to unhandled exception!
```

On inspection of the build dir, it seems that pyc files are not build included
![image](https://github.com/user-attachments/assets/cf72b247-baaa-4420-b308-eb8113f922b8)

**Comment by rushter** [comment]
Good idea. Are you familiar with hooks?

**Comment by baseplate-admin** [comment]
> Good idea. Are you familiar with hooks?

Unfortunately i am not very familiar with hooks.

But the maintainer of pyinstaller replied in this discussion on how this can be added.

https://github.com/orgs/pyinstaller/discussions/8703#discussioncomment-10220874

**Comment by rushter** [comment]
Added it
