### ISSUE TITLE
Add wheel for 3.13?

### ISSUE THREAD

**Issue by baseplate-admin** [rushter/selectolax#124]
Hi, it seems the 3.13 is soon to launch. Do you have any plans to release for 3.13?

**Comment by baseplate-admin** [comment]
At the same time support for 3.7, 3.8 can be dropped

**Comment by baseplate-admin** [comment]
Hi, @rushter , sorry for ping but can you please release it?

Now that python 3.13 is on the horizon?

**Comment by rushter** [comment]
Python 3.13 is not available on CI yet.

https://github.com/rushter/selectolax/actions/runs/11236017337

**Comment by baseplate-admin** [comment]
This is weird, cause of this: https://github.com/actions/python-versions/releases

It has `3.13.0`

**Comment by baseplate-admin** [comment]
Blocked by 
- https://github.com/actions/python-versions/pull/312

**Comment by rushter** [comment]
In order to make a new release, we need to make sure that nothing breaks when switching to Cython 3.0. 
https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

**Comment by rushter** [comment]
Build fails for Windows, will investigate it later https://github.com/rushter/selectolax/actions/runs/11239896149/job/31248003297

**Comment by char101** [comment]
`pip wheel` uses an virtual env to build and does not use the existing cython. Using `pip install setuptools && python setup.py bdist_wheel` works.

**Comment by rushter** [comment]
@char101 Are you sure? We had no problems previously

**Comment by char101** [comment]
I just clone the repo previously.

First I built using setuptools, no problem. 

And then I removed the cython generated .c source, then run `pip wheel .` which resulted in failure due to `parser.c` not found.

The only different I can see is that `pip wheel .` is running setuptools in a venv.

**Comment by rushter** [comment]
@char101 Thank you, it helped.

**Comment by baseplate-admin** [comment]
Closing as completed.

Thanks: @rushter , @char101
