### ISSUE TITLE
Node.replace_with() doesn't work with <head> and <body> tags

### ISSUE THREAD

**Issue by JuroOravec** [rushter/selectolax#128]
### Context

For [django_components](https://github.com/EmilStenstrom/django-components) we need to insert `<link>` and `<script>` tags at the end of `<head>` and `<body>` nodes (respectively) of a full HTML document.

I decided to use the Lexbor parser. However, there is no direct API to insert nodes inside other nodes, so I made a workaround as outlined here https://github.com/rushter/selectolax/issues/126.

But the problem is that while this workaround works with normal nodes, it does NOT work when I want to insert nodes into `<body>` and `<head>`. In other words, `elem.replace_with(new_elem_node)` does not work with `<body>` and `<head>`.

### Workaround

I made a workaround as below, where I first escape the `<!doctype>`, `<html>`, `<body>`, and `<head>` tags, so instead the parser treats them as custom HTML tags. Only then I can mutate the nodes as I woud have normally done.

But for my workaround, I need to regex-replace the HTML once before parsing it with lexbor, and once after. This defeats the performance gains, and mutating the HTML with Lexbor ends up roghly the same as with lxml:

```
==== Total trials: 5000 =====
LEXBOR - Total time: 25.8
LXML - Total time: 24.9
```

The workaround to mutate `<body>` / `<head>` tags:

```py
HTML_ROOT_TAGS_REGEX = re.compile(
    r"<!doctype|<html|</html|<head|</head|<body|</body",
    re.IGNORECASE,
)

HTML_ROOT_TAGS_REVERSE_REGEX = re.compile(
    r"<doctype_|<html_|</html_|<head_|</head_|<body_|</body_",
    re.IGNORECASE,
)

html_tag_escapes: Dict[str, str] = {
    "<!doctype": "<doctype_",
    "<html": "<html_",
    "</html": "</html_",
    "<head": "<head_",
    "</head": "</head_",
    "<body": "<body_",
    "</body": "</body_",
}
html_tag_escapes_reverse = {val: key for key, val in html_tag_escapes.items()}


class TransformHtmlCallback(Protocol):
    def __call__(self, head: Optional[LexborNode], body: Optional[LexborNode]) -> None: ...  # noqa: #704


def transform_html_document(html: str, transform: TransformHtmlCallback) -> str:
    # Escape <!doctype>, <html>, <head>, and <body> tags, because Selectolax treats them
    # specially, which makes it impossible to edit them.
    def on_replace_match(match: "re.Match[str]") -> str:
        match_str = match[0].lower()
        return html_tag_escapes[match_str]

    escaped_html = HTML_ROOT_TAGS_REGEX.sub(on_replace_match, html)

    # Selectolax now treats the escaped tags as custom tags, and so Selectolax wraps
    # the whole content in extra <html><head></head><body> CONTENT </body></html>.
    # So the actual HTML is under `.body.child`
    wrapper_tree = LexborHTMLParser(escaped_html).body
    escaped_tree = wrapper_tree.child if wrapper_tree else None
    if escaped_tree:
        body_matches = escaped_tree.css("body_")
        head_matches = escaped_tree.css("head_")
        body = body_matches[0] if body_matches else None
        head = head_matches[0] if head_matches else None
    else:
        body = None
        head = None

    # Finally, we can pass the actual <head> and <body> tags to be transformed
    # The transformations happen in-place in Selectolax.
    transform(head, body)
    transformed_html = cast(str, escaped_tree.html) if escaped_tree else ""

    # After the transformations are applied, we need to un-escape the <doctype_>, <head_>, etc tags
    def on_reverse_replace_match(match: "re.Match[str]") -> str:
        match_str = match[0].lower()
        return html_tag_escapes_reverse[match_str]

    final_html = HTML_ROOT_TAGS_REVERSE_REGEX.sub(on_reverse_replace_match, transformed_html)

    # NOTE: Because of how we work around selectolax to enable modifying the <body> and <head>
    # tags, selectolax also adds `</doctype_>` at the end of the content when we serialize the HTML.
    # So we have to remove that.
    return final_html[:-11]
```

### Next steps

I'm doing `LexborNode.replace_with()` only because the lexbor binding doesn't expose a way to insert one node into another. So if that was possible.

IMO this issue consists of 2 parts:
1. Allowing to insert nodes one into another, as mentioned in https://github.com/rushter/selectolax/issues/126.
2. After step 1., try `LexborNode.insert_child()` with `<head>` and `<body>`, and see if it works or not. If NOT, this issue will be relevant.

As for part 1, I looked around selectolax and lexbor, and found that lexbor defines [`lxb_dom_node_insert_child`](https://github.com/lexbor/lexbor/blob/72236d31da1a4c3d83c621446dcf4f70345fda05/source/lexbor/dom/interfaces/node.c#L385), which does what I'm looking for.

It looks that adding support for `LexborNode.insert_child` should be matter of copy-pasting code of another method, like [`LexborNode.insert_before`](https://github.com/rushter/selectolax/blob/4370cddf04a6ed3e8cad97f2d588bb5f6c854511/selectolax/lexbor/node.pxi#L556), and just modifying the function calls. So that's something I can make a PR for.

However, for the step 2, I am out of my depth, and would need some help figuring out what could be the cause and what to do with it.

@rushter Let me know what you think about adding support for `LexborNode.insert_child`

**Comment by rushter** [comment]
Hi, sure, let's add it.
