### ISSUE TITLE
How to create a new LexborNode and insert it into an empty LexborHTMLParser

### ISSUE THREAD

**Issue by wnm3** [rushter/selectolax#133]
I am trying to replace bs4 code with selectolax but I can't find the equivalent of new_tag("th") to create a new table header tag. I also can't figure out how to create a fragment of HTML without the  html, head, and body tags. I also don't know how to insert new elements at an index position in the children of a Node. Any help is appreciated.

**Comment by rushter** [comment]
Unfortunately, it's not possible right now. Relevant issue https://github.com/rushter/selectolax/issues/74

**Comment by rushter** [comment]
> Thank you for the response. Hmm, there must be a way to extend existing HTML by adding new elements.
> 
> My use case is to change a table that had used colspan=2 and remove that attribute, substituting a new cell that replicates the value. Do you think it is possible for me to create a document with the added HTML, head, and body tags to retrieve the Node from that and then try to add it to another document in the proper location? The insertion would need to change the parent, etc.
> 
> I also have a lot of simple tests for parsing that have mere fragments of HTML that I want to parse. I can work around those by stuffing them in the html, head, and body wrapper.

For attributes, you can just use `attrs` which modified attributes in place.
You can also replace selected node or insert new nodes using `replace_with`, `insert_before`, `insert_after`, `insert_child`.
Those methods accept either an HTML string or a Node from a different document.

**Comment by wnm3** [comment]
Thank you. I'd missed that I could pass HTML into those methods.

**Comment by lexborisov** [comment]
@wnm3 @rushter 

What's the problem with using element creation? Maybe I misunderstood something?
There are functions 
```C
lxb_inline lxb_html_element_t *
lxb_html_document_create_element(lxb_html_document_t *document,
                                 const lxb_char_t *local_name, size_t lname_len,
                                 void *reserved_for_opt);
```

There is fragment parsing, but this is when you need to parse HTML.
```C
LXB_API lxb_dom_node_t *
lxb_html_parse_fragment(lxb_html_parser_t *parser, lxb_html_element_t *element,
                        const lxb_char_t *html, size_t size);
```

**Comment by lexborisov** [comment]
Hi @JuroOravec 

1. All memory is allocated from the document. This is where the document is passed to the share to associate memory with the document. You will need to insert the node/item into the tree yourself. Please, see https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/node.h#L94 and so on.
2. Yes.
