### ISSUE TITLE
Type annotation for Selector class functions

### ISSUE THREAD

**Issue by bosmobosmo** [rushter/selectolax#147]
According to the type annotation, the `Selector` class contains these two functions: `any_attribute_long_than` and `attribute_long_than`.
https://github.com/rushter/selectolax/blob/master/selectolax/parser.pyi#L56

However, in the documentation, it's written that the class have the functions `any_attribute_longer_than` and `attribute_longer_than`.

Using `long_than` instead of `longer_than` results in an `AttributeError` so I think it's an error in the type annotation.

**Comment by rushter** [comment]
Thanks.
