### ISSUE TITLE
`_Attributes.get` is incorrectly typed

### ISSUE THREAD

**Issue by ThirVondukr** [rushter/selectolax#150]
It seems like `_Attributes.get` is incorrectly typed there: https://github.com/rushter/selectolax/blob/814be56ab3d8bf65184bb1425b10775dcb5035ab/selectolax/parser.pyi#L18-L19
shouldn't it return `DefaultT | str` instead in this overload?

**Comment by ThirVondukr** [comment]
An a side note - shouldn't `_Attributes.__getitem__` raise a KeyError if key was not found to be consistent with how `dict` behaves? It's really frustrating to use with a type checker with this current behavior 🤔

**Comment by rushter** [comment]
> An a side note - shouldn't `_Attributes.__getitem__` raise a KeyError if key was not found to be consistent with how `dict` behaves? It's really frustrating to use with a type checker with this current behavior 🤔

You are right, a PR with fixes will be appreciated.

**Comment by ThirVondukr** [comment]
@rushter PR with what fix exactly? I'm willing to try to fix typing but I'm unlikely to touch cython 😅 
`css_first` doesn't seem to be typed correctly too, shouldn't it return `Node | None`?
```py
from selectolax.parser import HTMLParser

parser = HTMLParser("")
reveal_type(parser.css_first(".something"))  # note: Revealed type is "selectolax.parser.Node"
```

**Comment by ThirVondukr** [comment]
Also changing behavior of `__getitem__` would be a breaking change

**Comment by rushter** [comment]
> Also changing behavior of `__getitem__` would be a breaking change

It returns KeyError already, I thought you wanted to make it clear in the docs.

**Comment by ThirVondukr** [comment]
Oh, wait, attribute values can be none 🤦‍♂️, e.g. `<img some-attr/>`?

**Comment by rushter** [comment]
> Oh, wait, attribute values can be none 🤦‍♂️, e.g. `<img some-attr/>`?

Yes

**Comment by ThirVondukr** [comment]
Sorry for the confusion, current typing makes total sense then

**Comment by ThirVondukr** [comment]
> @rushter PR with what fix exactly? I'm willing to try to fix typing but I'm unlikely to touch cython 😅 `css_first` doesn't seem to be typed correctly too, shouldn't it return `Node | None`?
> 
> ```python
> from selectolax.parser import HTMLParser
> 
> parser = HTMLParser("")
> reveal_type(parser.css_first(".something"))  # note: Revealed type is "selectolax.parser.Node"
> ```

@rushter This still seems to be a mistake then?
https://github.com/rushter/selectolax/blob/f0825ae1e041cc3480e0a32c717a7af048e945cb/selectolax/modest/node.pxi#L491

**Comment by ThirVondukr** [comment]
Example of how it should be typed from stdlib: https://github.com/python/typeshed/blob/98f070a8f86a5c6f4e87ae64ec5c6d377662d0fd/stdlib/collections/__init__.pyi#L110-L114
