### ISSUE TITLE
Possible slow results when getting hrefs from document

### ISSUE THREAD

**Issue by sezginriggs** [rushter/selectolax#16]
Hello,

I'm using selectolax instead of lxml now and I have 20% performance increase already. But I wonder if it's possible to make it faster by using .css() or something else.

I'm getting tags with `tags = self.__selectolax_tree.tags('a')`  and getting their attributes, if attribute has "href", i use this url for further needs.

Should I use css() instead of tags() for getting links too?

**Comment by rushter** [comment]
I think you will get the same speed. It is much easier to benchmark it on your particular data.
I'm not an expert in the underlying [Modest](https://github.com/lexborisov/Modest/) library.
