### ISSUE TITLE
errors while installing... not a pro....

### ISSUE THREAD

**Issue by bwashed** [rushter/selectolax#19]
While am trying to install selectolax i get the following errors:

pip3 install selectolax
Collecting selectolax
  Using cached selectolax-0.2.3.tar.gz (1.3 MB)
Installing collected packages: selectolax
    Running setup.py install for selectolax ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-install-epj3y_9p/selectolax/setup.py'"'"'; __file__='"'"'/private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-install-epj3y_9p/selectolax/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-record-0vt0jize/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/selectolax
         cwd: /private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-install-epj3y_9p/selectolax/
    Complete output (60 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/selectolax
    copying selectolax/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    running egg_info
    writing selectolax.egg-info/PKG-INFO
    writing dependency_links to selectolax.egg-info/dependency_links.txt
    writing top-level names to selectolax.egg-info/top_level.txt
    reading manifest file 'selectolax.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'CONTRIBUTING.rst'
    warning: no files found matching 'HISTORY.rst'
    warning: no previously-included files found matching 'selectolax/*.so'
    warning: no files found matching 'modest/include/*'
    warning: no files found matching 'modest/source/*'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    warning: no files found matching '*.jpg' under directory 'docs'
    writing manifest file 'selectolax.egg-info/SOURCES.txt'
    copying selectolax/node.pxi -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    copying selectolax/parser.c -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    copying selectolax/parser.pxd -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    copying selectolax/parser.pyx -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    copying selectolax/selector.pxi -> build/lib.macosx-10.9-x86_64-3.8/selectolax
    running build_ext
    building 'selectolax.parser' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/selectolax
    creating build/temp.macosx-10.9-x86_64-3.8/modest
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest/render
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest/style
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest/layer
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest/finder
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/modest/node
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myurl
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myfont
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myport
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myport/posix
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myport/posix/mycore
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myport/posix/mycore/utils
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/property
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/values
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/namespace
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/selectors
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/declaration
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycss/media
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myencoding
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycore
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/mycore/utils
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myhtml
    creating build/temp.macosx-10.9-x86_64-3.8/modest/source/myunicode
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Imodest/include/ -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c selectolax/parser.c -o build/temp.macosx-10.9-x86_64-3.8/selectolax/parser.o -DMODEST_BUILD_OS=Darwin -DMyCORE_OS_Darwin -DMODEST_PORT_NAME=posix -DMyCORE_BUILD_WITHOUT_THREADS=YES -DMyCORE_BUILD_DEBUG=NO -O2 -pedantic -fPIC -Wno-unused-variable -Wno-unused-function -std=c99
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-install-epj3y_9p/selectolax/setup.py'"'"'; __file__='"'"'/private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-install-epj3y_9p/selectolax/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/24/269pxf1s6gdd4jrdm0lxy3f40000gq/T/pip-record-0vt0jize/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/selectolax Check the logs for full command output.

Why do i get such error? Thanks a lot for helping out...

**Comment by rushter** [comment]
Hi, have you tried this?
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by bwashed** [comment]
@rushter thanks a lot for helping out.

So, basically, as written in the link you suggested 
"The problem is that one needs to explicitly agree to the license agreement."
once I accept the license as far as XCode or Command Line Tools it should work?

As written am not a pro, simply curious and willing to understand slightly better. 
As i can see, the output i got on the terminal state @ certain point: "error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun..........."

Thanks a lot....

Best Regards,
Emil

**Comment by bwashed** [comment]
@rushter 
...... your solution worked..... many many many thanks.....

Still missing what is behind it, but happy it worked :-)
