### ISSUE TITLE
When using selectolax parser to get video tags, 'attrs' is empty and can get video's src

### ISSUE THREAD

**Issue by noambaron1989** [rushter/selectolax#21]
I'm tring to run the following logic:

>     videos = []
>     try:
>         bs_videos = parser.css('video')
>         for bs_video in bs_videos:
>             logger.debug('found video attribute: %s', str(bs_video))
>             if 'src' in bs_video.attrs:
>                 try:
>                     video = bs_video.attrs['src']
>                     video = urllib.parse.urljoin(site_url, video)
>                     logger.debug('found video attribute: %s', video)
>                     if is_valid_file(logger, video, Constants.image_files):
>                         logger.debug('file video %s is valid!', video)
>                         videos.append(video)
>                 except Exception as e:
>                     continue
>     except Exception as e:
>         logger.error("exception finding video files in page. %s", str(e),
>                      pars={Logger.key_job_id: job_id})
>     return videos

When I get video tag , I do get a selectolax.parser.Node  object but the 'attrs' dict is empty when debugging. How do I get the video 'src'? (we never get in "if 'src' in video.attrs:")

for example:
If I want to get the video 'src' from the following html, how should I do it?

> <video width='320' height='240' controls=''\><source src='movie2.mp4' type='video/mp4'\></video>

**Comment by rushter** [comment]
Please close if resolved.

**Comment by noambaron1989** [comment]
Please see an example: https://dumpz.org/aBDkpZ3STSZ8
