### ISSUE TITLE
Node.Replace_with automatically encodes everything

### ISSUE THREAD

**Issue by Dantenerosas** [rushter/selectolax#26]
For example,
I'm replacing following block 

> ... \<div data-mutable-id="some_id"\>

using Node.Replace_with which results in 

>  \&lt;div data-mutable-id="some_id"\&gt;

inside HTMLParser.html. It's kinda critical because I'm using selectolax only for replacing html block and it's actually messes with the selectolax's ability to find specified block if another change to it is requried later

**Comment by rushter** [comment]
The current version of `replace_with` is limited to plain-text only. That's why your tags are encoded.
See #25 for progress on this issue.

**Comment by Dantenerosas** [comment]
> 
> 
> The current version of `replace_with` is limited to plain-text only. That's why your tags are encoded.
> See #25 for progress on this issue.

I see. Is there any way to circumvent it for now? Or everything will break if encoding is removed?

**Comment by rushter** [comment]
> I see. Is there any way to circumvent it for now? Or everything will break if encoding is removed?

What do you mean by removing encoding? I don't think it's possible to circumvent it somehow, the Modest engine serializes all the tree when you change something. And it knows which nodes are plain-text.

If you want a quick fix, you can compile #25 and use `node_replace_with`.

**Comment by Dantenerosas** [comment]
> 
> 
> > I see. Is there any way to circumvent it for now? Or everything will break if encoding is removed?
> 
> What do you mean by removing encoding? I don't think it's possible to circumvent it somehow, the Modest engine serializes all the tree when you change something. And it knows which nodes are plain-text.
> 
> If you want a quick fix, you can compile #25 (`python setup.py install`) and use `node_replace_with`.

I'll try that, thanks

**Comment by rushter** [comment]
Resolved via #25
