### ISSUE TITLE
New replace_with method does not work as expected

### ISSUE THREAD

**Issue by rushter** [rushter/selectolax#27]
I noticed an issue regarding reference. The following code works:
```python
from selectolax.parser import HTMLParser

html_parser = HTMLParser('<div>Get <span alt="Laptop"><img src="/jpg"> <div></div></span></div>')
img_node = html_parser.css_first('img')

html_parser2 = HTMLParser('<div>Test</div>')
img_node.replace_with(html_parser2.body.child)
assert html_parser.body.child.html == '<div>Get <span alt="Laptop"><div>Test</div> <div></div></span></div>'
```

but the following fails:
```python
from selectolax.parser import HTMLParser

html_parser = HTMLParser('<div>Get <span alt="Laptop"><img src="/jpg"> <div></div></span></div>')
img_node = html_parser.css_first('img')

img_node.replace_with(HTMLParser('<div>Test</div>').body.child)
assert html_parser.body.child.html == '<div>Get <span alt="Laptop"><div>Test</div> <div></div></span></div>'
```

since this is python, I would expect the two to work the same and are memory safe

_Originally posted by @ppwwyyxx in https://github.com/rushter/selectolax/pull/25#issuecomment-668200521_

**Comment by rushter** [comment]
https://github.com/rushter/selectolax/pull/25#issuecomment-668206627

**Comment by rushter** [comment]
@lexborisov What is the best way to copy a subtree (a node and all its child nodes) from one tree to another? Are there any helpers?

**Comment by lexborisov** [comment]
In the current version, there is no way to copy nodes from one tree to another.
Trees have a different memory pool. When cloning nodes, we need to compare `node->tree` pointer, and if they do not match, then copy using the memory of the tree into which the insertion is made.

I can add this functionality to the myhtml: 
```C
myhtml_node_t * myhtml_node_clone(myhtml_tree_t *dest_tree, myhtml_node_t *src);
myhtml_node_t * myhtml_node_clone_deep(myhtml_tree_t *dest_tree, myhtml_node_t *src);
```

What do you think about it?

**Comment by rushter** [comment]
> What do you think about it?

That would be cool. Is it safe to use two trees and insert a node from another tree?

**Comment by lexborisov** [comment]
> That would be cool. Is it safe to use two trees and insert a node from another tree?

Yes, it will look something like this:
```C
myhtml_node_t *cloned;

cloned = myhtml_node_clone(dest_node->tree, src);
if (cloned == NULL) {
    /* ... */
}

myhtml_tree_node_insert_after(dest_node, cloned);
```

**Comment by rushter** [comment]
I've published a simple fix now. We definitely want to make it more robust in the future by copying nodes.

This example does not work for some reason:
```
            node = myhtml_tree_node_clone(<myhtml_tree_node_t *> value.node)
            myhtml_node_insert_before(left_node, node)
            myhtml_node_delete(left_node)
```
I haven't debugged it, but the inserted node gets lost. 

Currently, we use two trees, but this is fragile and there are so many ways to break it.

**Comment by lexborisov** [comment]
@rushter 

I have [added two functions](https://github.com/lexborisov/myhtml/blob/master/include/myhtml/api.h#L1171), please try it.

**Comment by rushter** [comment]
@lexborisov Thanks! It works as expected.
