### ISSUE TITLE
'Node.unwrap_tags' accepts only 'list' as argument

### ISSUE THREAD

**Issue by mush42** [rushter/selectolax#28]
Hi,

I don't know if this has any effect, but 'Node.unwrap_tags' should accept any iterable rather than only lists.

The following exception is raised when calling Node.unwrap_tags with a set:
```shell
    html.body.unwrap_tags({'a', 'span', 'div',})
TypeError: Argument 'tags' has incorrect type (expected list, got set)

```

**Comment by rushter** [comment]
I'm not sure if it makes sense to allow arbitrarily iterables. It's strongly typed for speed.

**Comment by mush42** [comment]
Got it. I'm willing to work under some constraints if it make things faster.
