### ISSUE TITLE
Do not support ">" in standard css selector

### ISSUE THREAD

**Issue by ClericPy** [rushter/selectolax#29]
```python
# -*- coding: utf-8 -*-
from bs4 import BeautifulSoup

html = '<div><p>text</p></div>'
node = BeautifulSoup(html, 'html.parser')
print(node.select_one('div p').text)
# text
print(node.select_one('div>p').text)
# text

from selectolax.parser import HTMLParser

html = '<div><p>text</p></div>'
node = HTMLParser(html)
print(node.css_first('div p').text())
# text
print(node.css_first('div>p').text())
# ValueError: Bad CSS Selectors: div>p

```

**Comment by rushter** [comment]
Please use spaces as recommended in CSS specifications.

**Comment by ClericPy** [comment]
> Please use spaces as recommended in CSS specifications.
> 
> It's better to submit this to [Modest](https://github.com/lexborisov/Modest/) that performs the actual parsing of CSS.

OK.

The `>` is not same as `space` when I want to query the direct children. If `Modest` will not support this usage, I can abandon that habbit.

Thanks for your answering

https://stackoverflow.com/questions/2636379/what-is-the-difference-between-and-a-space-in-css-selectors

**Comment by rushter** [comment]
> The > is not same as space when I want to query the direct children. If Modest will not support this usage, I can abandon that habbit.

I meant that `print(node.css_first('div > p').text())` will work as expected.
