### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by NecroKote** [rushter/selectolax#3]
Hi Artem,
Thank you for your hard work!

I've tried to use selectolax on a windows machine but got a number of issues installing your package:
- default compiler flags, that are not supported by VC compiler (`-Wno-unused-variable, `-Wno-unused-function`)
- flags, ignored by VC complier (`-pedantic`, -fPIC, -std=c99)

Even after removing unsupported flags, compilation failed with "<io.h> file not found" that came from python's `pyconfig.h`.

- Windows 10 x64 
- VC Built Tools 2017 v15.7.1
- Python 3.6.4 x64

**Comment by rushter** [comment]
Hi!

I've fixed setup config for Windows.
I'm not very experienced with Windows, but I successfully build `selectolax` using:

Windows 10 x32
Python 3.6 with anaconda distribution
MSVC 14.11 

You probably need to install right version Microsoft toolsets where they have correct headers for Python 3.6. 


You can try to install Cython and install selectolax using `python setup.py install --cython`. Maybe this will help. 

Or maybe this could help: https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory

**Comment by NecroKote** [comment]
Artem, thank you for quick fix!

Issue solved with 00ee2c42fdcd2a2b40b86b4b97f2501d473af14f and installind **Windows 10 SDK** on my side

**Comment by cebaa** [comment]
@rushter Perhaps worth setting up https://github.com/joerick/cibuildwheel or similar to get the CI to build wheels for you for all platforms at once.

**Comment by rushter** [comment]
@cebaa Thank you for your suggestion. I've already added a pipeline for wheel building: 0e5728b5c619e
I planned to upload them for the next release.

**Comment by cebaa** [comment]
@rushter Awesome news, thank you!
