### ISSUE TITLE
Segmentation fault with unwrap_tags

### ISSUE THREAD

**Issue by satchamo** [rushter/selectolax#32]
First, thanks for writing and maintaining this speedy library. It makes a _huge_ difference when parsing thousands of documents compared to other parsers.

Anyway, while attempting to strip the `data` tag from some content, I noticed that the library seems to choke on this specific tag. Here's some code to reproduce it:

```python
from selectolax.parser import HTMLParser
html = """test"""
tree = HTMLParser(html)
tree.unwrap_tags(["data"])
```
Output: Segmentation fault (core dumped)

I'm running `selectolax==0.2.6` on `Python 3.6.9`

**Comment by rushter** [comment]
I've fixed the problem in 0.2.10.
