### ISSUE TITLE
Python 2 Support

### ISSUE THREAD

**Issue by dan-kez** [rushter/selectolax#33]
Hey all!

Quick question - does this library work with python 2.7 by chance? Haven't seen much documentation around version support so just want to check in. We're almost done with our upgrade to 3 but this would potentially be a substantial performance boost.

**Comment by rushter** [comment]
There is no support for Python 2, but it's pretty easy to compile selectolax under Python 2.
The only thing that you would need to adjust is `language_level=3` in the source code.
