### ISSUE TITLE
text() method does not strip some tags and some javascript code

### ISSUE THREAD

**Issue by mpage-uga** [rushter/selectolax#4]
text() method does not strip some tags and some javascript code.
Try for example on: https://www.amphenol-socapex.com/fr/taxonomy/term/4109/application/ethernet-4215.html

**Comment by rushter** [comment]
You need to strip them manually.

```
def get_text(html):
    tree = HTMLParser(html)

    if tree.body is None:
        return None

    for tag in tree.css('script'):
        tag.decompose()
    for tag in tree.css('style'):
        tag.decompose()

    text = tree.body.text(separator='\n')
    return text
```

**Comment by lexborisov** [comment]
@mpage-uga 
In [html spec serialization](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) in `If current node is a Text node` section:

> `If current node is a Text node`
> If the parent of current node is a style, script, xmp, iframe, noembed, noframes, or plaintext element, or if the parent of current node is a noscript element and scripting is enabled for the node, then append the value of current node's data IDL attribute literally.
>
> Otherwise, append the value of current node's data IDL attribute, escaped as described below.

**Comment by mpage-uga** [comment]
Perfect !
Thanks for this very good tool.
