### ISSUE TITLE
Fix text extraction for lexbor

### ISSUE THREAD

**Issue by rushter** [rushter/selectolax#44]
In some cases, it segfaults

**Comment by lexborisov** [comment]
@rushter 

Is this a problem on my side?

**Comment by rushter** [comment]
> @rushter
> 
> Is this a problem on my side?

I don't think so, I need to check. I don't use text extraction function from lexbor, because it lacks the `separator` (whitespace or new line) parameter which is very useful for real-world HTML where whitespaces can be added via CSS styles.
