### ISSUE TITLE
`<!DOCTYPE ...>` is not preserved during parsing

### ISSUE THREAD

**Issue by vidhu** [rushter/selectolax#46]
When you try to parse a document with a `<!DOCTYPE ...>` tag and serialize it, the doctype is removed

```python
html = """
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
    </head>
    <body>
        <p>Hello World</p>
    </body>
</html>
"""

from selectolax.parser import HTMLParser
doc = HTMLParser(html)

print(doc.html)
```
The output is missing the Doctype.
```html
<html><head>
        <title>Test</title>
    </head>
    <body>
        <p>Hello World</p>
    
</body></html>
```

Anything I'm doing wrong or maybe using the wrong api/attribute?

**Comment by rushter** [comment]
Since the parsing engines behind the selectolax follow all the standards, they omit the doctype. 
Not sure if we can retrieve the original doctype, I need to check. In HTML5, the doctype is the same for all websites.

You can test it in Chrome/Firefox devtools: `document.documentElement.outerHTML` returns no doctype.

**Comment by vidhu** [comment]
Thanks for your response. What do you mean by "follow all the standards"? Unless theres a standards which states that the doctype is not part of the document (very unlikely) I think it should be included. This would also be inline with what other parsers do

A doctype is not part of the documentElement, it's part of the document. You can verify this in devtools `document.doctype`

**Comment by rushter** [comment]
I will add doctype, but most likely, only next week.

**Comment by rushter** [comment]
I made a simple fix, please test it.

**Comment by vidhu** [comment]
I'll test it within 24hr and report back. Thank you!
