### ISSUE TITLE
Development of Lexbor

### ISSUE THREAD

**Issue by Okroshiashvili** [rushter/selectolax#48]
Hi @rushter 

First of all thanks for all your amazing work.

I've noticed that the development of Modest engine is slowed down and instead lexbor is developed. This is what @lexborisov suggests to use over the Modest engine. What happens to selectolax? Are you planning to continue supporting lexobor engine or stick with Modest engine?

**Comment by rushter** [comment]
Personally, I use Modest, because I need to work with arbitrary pages from different websites.
If you scrape specific websites and can validate the results, I think it's safe to use lexbor.

The reason I don't use lexbor yet is because it's not as tested as Modest (by the users).

**Comment by Okroshiashvili** [comment]
Thanks a lot. That's the answer I was looking for. I have thousands of pages to scrape not knowing their structure in advance. Greatly appreciate your work.
