### ISSUE TITLE
segmentation fault (core dumped) on particular, large html input

### ISSUE THREAD

**Issue by mleue** [rushter/selectolax#5]
Hey! First of all, thanks a lot for this cool project, it's really very convenient and speedy.

However, I have encountered an issue that python just dies when selectolax tries to get the text from some particular, quite large HTML inputs.
It doesn't throw an exception, it just dies. (I guess there is probably something going wrong in the C extension, not in the python parts of this package?)

I've attached an example file.
[selectolax_bug.log](https://github.com/rushter/selectolax/files/2420450/selectolax_bug.log)

Some things I've already tried that don't seem to be the problem:
- incomplete html tags (the attached file just terminates suddenly without properly closing all tags, however selectolax seems to handle those cases just fine otherwise)
- raw file/input size (I've seen selectolax successfully handle inputs of even double the size of the attached file, so that doesn't seem to be the issue either)

One idea I'm currently having:
- it might be related to the number of nodes (the test file contains several thousands of small `option` nodes) -> maybe selectolax chokes on the amount of nodes?

Code to recreate the issue:
```
with open('selectolax_bug.log') as f:
    html = f.read()

from selectolax.parser import HTMLParser
tree = HTMLParser(html)
text = tree.body.text() # here it just dies for me
```

**Comment by rushter** [comment]
What version of the selectolax and Python are you running on? 
I tried your example and it works fine for me. 

I changed the open command, since Python 3 is very strict about this. 
 `open('selectolax_bug.log', encoding='utf-8')` 
```

 
  
    
             
       Eintrag hinzufügen
      |  Administration
    
   
   
     Donnerstag, 16. August 2018 02:03Willkomen in unserem Gästebuch. Hier können Sie einen Beitrag hinterlassen.
     




Gästebuch
606911-606920
606901-606910
606891-606900
606881-606890
606871-606880
606861-606870
606851-606860
606841-606850
606831-606840
....
....
....
```

**Comment by rushter** [comment]
I'll check it this weekend.

**Comment by mleue** [comment]
perfect, thanks in advance for your time and effort

**Comment by rushter** [comment]
I pushed the fix, it's not very clever and depends on the compiler, but it should work on most of the systems. I will rewrite my text parsing algorithm in the future. Currently, it uses recursion approach and fails on your example because of the stack size limits. 

You can fix the old version by simply increasing the stack size:
```
➜  ~ ulimit -s
8192
➜  ~ ulimit -s 16000
➜  ~ ulimit -s
16000
```

Please try the new version:
> pip install --no-cache-dir selectolax==0.1.8

**Comment by rushter** [comment]
My fix relies on a compiler and it can ignore my instruction. I will fix this issue later.

For the time being you could use something like this:
```
>>> import resource
>>> soft, hard = resource.getrlimit(resource.RLIMIT_STACK)
>>> resource.setrlimit(resource.RLIMIT_STACK, (soft * 4, hard))
>>>
```

The code above increases the stack limit from 8kb to 32kb.

**Comment by mleue** [comment]
that works, perfect.
Again, thanks a lot for your time and effort.

**Comment by mindscratch** [comment]
@rushter was there any work done on this since the ticket was closed?

**Comment by mindscratch** [comment]
Yes, using selectolax 0.1.10 with python 3.6.6 (on CentOS 7 kernel 4.18) and html content that's ~14mb.

Using the rlimit hack in the python code has worked so far.

**Comment by rushter** [comment]
@mindscratch I've fixed the problem. Can you please check?

**Comment by lemonsoftltd** [comment]
Hello, i tried steps for my Centos 7. I couldn't install.

**Comment by rushter** [comment]
@lemonsoftltd You need to install the `python-devel` package.

Something like `yum install python-devel` or `yum install python3-devel` should fix the problem.

**Comment by lemonsoftltd** [comment]
Thanks for reply. They are already installed. However I tried to install.

```
[root@dhpc09 ehealth]# yum install python-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repo.boun.edu.tr
 * epel: repo.boun.edu.tr
 * extras: repo.boun.edu.tr
 * remi-php70: mirrors.uni-ruse.bg
 * remi-php72: mirrors.uni-ruse.bg
 * remi-safe: mirrors.uni-ruse.bg
 * updates: repo.boun.edu.tr
Package python-devel-2.7.5-76.el7.x86_64 already installed and latest version
Nothing to do
You have new mail in /var/spool/mail/root
[root@dhpc09 ehealth]# yum install python3-devel
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repo.boun.edu.tr
 * epel: repo.boun.edu.tr
 * extras: repo.boun.edu.tr
 * remi-php70: mirrors.uni-ruse.bg
 * remi-php72: mirrors.uni-ruse.bg
 * remi-safe: mirrors.uni-ruse.bg
 * updates: repo.boun.edu.tr
No package python3-devel available.
Error: Nothing to do
```
Can I copy files from my Windows 10? In windows, it is installed and working.
