### ISSUE TITLE
Benchmark against google-gumbo based html5-parser

### ISSUE THREAD

**Issue by yifeikong** [rushter/selectolax#54]
I came across this library [html5-parser](https://github.com/kovidgoyal/html5-parser), which is based on Google's gumbo parser. Could this benchmark be added?

**Comment by rushter** [comment]
Ok, added to benchmark but I don't see any speed improvement. Maybe I'm doing something wrong.

https://github.com/rushter/selectolax/commit/9ce80ab8411b42a528a6401d63256672aa7ae314
