### ISSUE TITLE
Bug when using replace_with after doing some node.decompose() operations

### ISSUE THREAD

**Issue by HugoLaurencon** [rushter/selectolax#57]
Hello,

First thank you for your amazing library!

To be really short, I ran into a bug when using the `replace_with` method after using some `node.decompose()` operations.

Now, to be more precise, I am trying to simplify DOM trees.

So I designed two functions for this:
-one that deletes all nodes that do not contain a tag I want to keep
-and the second one that "un-nest" nodes, which means that `<div><div>Ok</div></div>` would simply become `<div>Ok</div>` because the first `div` is useless, since it contains only one child, with no text, and the only child has the same tag.

Here are the two functions.

```
import re

set_interesting_tags = set(["address", "article", "aside", "blink", "blockquote", "body", "br", "caption", "center", "dd", "dfn", "dl", "dt", "div", "figcaption", "h", "h1", "h2", "h3", "h4", "h5", "h6", "head", "header", "hgroup", "html", "legend", "li", "main", "marquee", "menu", "menuitem", "nav", "ol", "p", "section", "summary", "title", "ul", "audio", "embed", "figure", "iframe", "img", "object", "picture", "video", "source"])

def remove_digits_string(string):
    string = re.sub(r"\d+", "", string)
    return string

def remove_uninteresting_nodes(selectolax_tree):
    nodes_to_remove = [
        node
        for node in selectolax_tree.root.traverse()
        if remove_digits_string(node.tag) not in set_interesting_tags
    ]
    for node in nodes_to_remove:
        node.decompose()
    return selectolax_tree

def unnest_nodes(selectolax_tree):
    modification = True
    while modification:
        modification = False
        for node in selectolax_tree.root.traverse():
            children = [child for child in node.iter()]
            if len(children) == 1:
                child = children[0]
                if node.tag == child.tag:
                    text = node.text(deep=False).strip()
                    if not text:
                        node.replace_with(child)
                        modification = True
                        break
    return selectolax_tree
```

Now, when I am using some html files to make a tree, for example [this one](https://drive.google.com/file/d/1uXWT9WC5Wgod_PHMNYCLd3OQRWznL7C6/view?usp=sharing):

```
f = open("data_collection/html_reproduce_bug.txt", "r")
html_str = f.read()
f.close()
selectolax_tree = HTMLParser(html_str)
```

if I do
```
selectolax_tree = remove_uninteresting_nodes(selectolax_tree)
```
or
```
selectolax_tree = unnest_nodes(selectolax_tree)
```
or
```
selectolax_tree = unnest_nodes(selectolax_tree)
selectolax_tree = remove_uninteresting_nodes(selectolax_tree)
```
it works well, but if I do
```
selectolax_tree = remove_uninteresting_nodes(selectolax_tree)
selectolax_tree = unnest_nodes(selectolax_tree)
```
it looks like we are stuck in a `replace_with` operation after some iterations and the code never ends.

I think this had something to do with the `node.decompose()` operation, since I also had this bug when using before `unnest_nodes` another function than `remove_uninteresting_nodes`, but which also uses `node.decompose()`.

What is strange is that, after the `remove_uninteresting_nodes` function, if I remake a new tree using the html `selectolax_tree.html`, and then apply the `unnest_nodes` function, it works.

```
selectolax_tree = remove_uninteresting_nodes(selectolax_tree) 
selectolax_tree = HTMLParser(selectolax_tree.html)
selectolax_tree = unnest_nodes(selectolax_tree)
```

You can download everything needed to reproduce this easily [here](https://drive.google.com/drive/folders/1IqnJpGrQg5bw5AKROs_aIuchULVPbG_q?usp=sharing).

Thanks in advance.

**Comment by rushter** [comment]
Is it reproducible when you parse different HTML files?

Selectolax uses Modest directly, when removing nodes:
https://github.com/rushter/selectolax/blob/6b67223952e9416b2abc4baa8477159a3ad30aa3/selectolax/modest/node.pxi#L491-L494

I think your particular HTML file violates some of the standards and Modest can't process it properly.
If you have more example, please upload them too.

**Comment by rushter** [comment]
I think the real problem is that your function can call `decompose` on already removed objects.
You can try using `decompose(deep=False)`.

Unfortunately, selectolax is a very thin wrapper over Modest and it does not check for such problems.
I think removing the same node multiple times corrupts memory.

**Comment by HugoLaurencon** [comment]
Thank you, much clearer now!
