### ISSUE TITLE
node.text() does not account for </br>

### ISSUE THREAD

**Issue by mr-bjerre** [rushter/selectolax#59]
Thanks for `selectolax` - it's working great!

I have one question though. Is it possible to account for break lines? I'd expect the following to return `Hello\nWorld` instead of `HelloWorld`.

```python
from selectolax.parser import HTMLParser

parsed_html = HTMLParser("<h1>Hello<br/>World</h1>")
[node.text(deep=False, strip=False) for node in parsed_html.css("h1")]
```

**Comment by rushter** [comment]
You can replace all br tags before extracting text:

```
for node in parsed_html.css('h1 br'):
    node.replace_with('\n')
```
You can also use `text(..,separator='\n')` if you want to get new lines for every HTML tag.
