### ISSUE TITLE
Precompiled version

### ISSUE THREAD

**Issue by py-radicz** [rushter/selectolax#6]
Hello, at first thanks for awesome project!

Its not an issue at all, just question about distribution of package. Is there any way for users to install selectolax without c++ installed on windows platform? Any pointers to resources to read about that, will be appreciated.

**Comment by rushter** [comment]
Yes, you can precompile it into a Python wheel. Also, you can use something like Pyinstaller of Py2exe.

**Comment by py-radicz** [comment]
Thanks for pointing that out!
