### ISSUE TITLE
v3.8.9 typo?

### ISSUE THREAD

**Issue by mhillebrand** [rushter/selectolax#70]
<img width="175" alt="image" src="https://user-images.githubusercontent.com/286198/191063992-9b8ffb36-8a46-483f-b037-8bb0fa8547da.png">

**Comment by rushter** [comment]
Oops. Yeah, thank you for noticing me.

**Comment by mhillebrand** [comment]
Thanks for releasing v0.3.10. Will it be available via PyPI soon?

<img width="317" alt="image" src="https://user-images.githubusercontent.com/286198/191091683-2da687cd-8f30-4128-8f7f-778a95e32c30.png">

**Comment by mhillebrand** [comment]
Ah, thanks!
