### ISSUE TITLE
Why does selectolax ship Cython as install dependency?

### ISSUE THREAD

**Issue by baseplate-admin** [rushter/selectolax#83]
Hi there,

Thanks for creating selectolax. Is there any particular reason that you have cython as install dependency?

https://github.com/rushter/selectolax/blob/422b3ef1c98f58f3caed1962ed5254fc44572727/setup.py#L157

**Comment by rushter** [comment]
To compile old version of selectolax on a newer versions of Python. Some people pin their version of selectolax.
Every new major version of Python usually is not compatible with old C extensions.

**Comment by baseplate-admin** [comment]
Hi,

Thanks for quick response. 

> To compile old version of selectolax

Cant we have a minimum and maximum supported python version for a given version of `selectolax`? 

<sub>[Dependencies like `frozenlist` has a minimum python requirement](https://github.com/aio-libs/frozenlist/blob/ce5ace56faeaa2f6bfe1d6b5752f998c500b5b83/setup.cfg#L34)</sub>

**Comment by rushter** [comment]
Ok, I will think about it

**Comment by rushter** [comment]
Related issues cause by third party library https://github.com/rushter/selectolax/issues/38#issuecomment-861529400

**Comment by baseplate-admin** [comment]
Thanks for listening to my advice
