### ISSUE TITLE
Does `selectolax` support contains query ?

### ISSUE THREAD

**Issue by baseplate-admin** [rushter/selectolax#86]
Hi thanks for creating `selectolax`. I was considering if `selectolax` supports `contains` query.

Here's an example :

```python
from selectolax.parser import HTMLParser

html = """
<div>
  <p>Some text here</p>
  <p>Some more text here</p>
  <p>Yet more text</p>
</div>
"""

parser = HTMLParser(html)
nodes = parser.css('p:contains("text")')

for node in nodes:
    print(node.text())
```

Which returns : 

`zsh: segmentation fault (core dumped)  python test.py`

**Comment by baseplate-admin** [comment]
Closing per https://github.com/lexbor/lexbor/issues/181#issuecomment-1514261024

**Comment by AmericanY** [comment]
@baseplate-admin did you reached a solution for that case?

**Comment by baseplate-admin** [comment]
> @baseplate-admin did you reached a solution for that case?

Yes i did. Check : https://github.com/baseplate-admin/CoreProject/blob/927254e99af46eca860dabacad208e72a1d8861d/backend/shinobi/parser/anime.py#L60

**Comment by rushter** [comment]
We now support a new lexbor selector`lexbor-contains`:
```
from selectolax.lexbor import LexborHTMLParser
html = "<div><p>hello </p><p id='main'>lexbor is AwesOme</p></div>"
parser = LexborHTMLParser(html)
# Case insensitive search
results = parser.css('p:lexbor-contains("awesome" i)')
# Case-sensitive search
results = parser.css('p:lexbor-contains("AwesOme")')
assert len(results) == 1
assert results[0].text() == "lexbor is AwesOme"
```
