### ISSUE TITLE
Memory leak when using LexborHTMLParser

### ISSUE THREAD

**Issue by glowww** [rushter/selectolax#90]
Using `LexborHTMLParser` seems to cause a severe memory leak. 

If I run this simple script, the memory usage goes up to 2,114 MB. If I replace `LexborHTMLParser` with `HTMLParser`, the memory usage is only 3 MB.

```
import psutil

import requests
from selectolax.lexbor import LexborHTMLParser
from selectolax.parser import HTMLParser

response = requests.get("https://github.com/")

process = psutil.Process()

start = process.memory_info().rss

for _ in range(20000):
    LexborHTMLParser(response.text).css("a")
    memory_usage = int((process.memory_info().rss - start) / 1024 ** 2)
    print(f"Memory usage: {memory_usage:,}MB")
```

**Comment by rushter** [comment]
Thanks for the report. Fixed that. 
The new version should be automatically published to pypi in a few hours.
