### ISSUE TITLE
Segmentation fault with Lexbor engine

### ISSUE THREAD

**Issue by captify-dpawlowski** [rushter/selectolax#91]
Hi,

I've encountered a page that causes segmentation fault when using Lexbor engine (Modest does not crash).
The page is `https://www.radiokerry.ie/sport/kerry-racing-news-65-333925`.

I'm using Python 3.9/3.10, selectorlax v0.3.14.

Steps to reproduce:

```
import requests
r = requests.get('https://www.radiokerry.ie/sport/kerry-racing-news-65-333925')
import selectolax
tree = selectolax.lexbor.LexborHTMLParser(r.text)
# tree = selectolax.parser.HTMLParser(r.text) # Modest does not crash
# tree.strip_tags(['script', 'style', 'svg'], recursive=False) # try some operations
tree.html

[1]    88411 segmentation fault  python
```
[Kerry Racing News _ RadioKerry.ie.html.txt](https://github.com/rushter/selectolax/files/11721051/Kerry.Racing.News._.RadioKerry.ie.html.txt)

Thank you for your work!

**Comment by lexborisov** [comment]
@captify-dpawlowski 

[Fixed](https://github.com/lexbor/lexbor/commit/0c20fa99e3bf41b523a475212f747480fab848d0) in lexbor library.
Thanks for the report!

@rushter 
Please, try fixed code in selectolax.

**Comment by rushter** [comment]
Sorry for late update, this should be fixed.
