### ISSUE TITLE
Weird issue in rendering HTML

### ISSUE THREAD

**Issue by ManiMozaffar** [rushter/selectolax#94]
Hey,
I'm writing a scraping library, which also leverages selectolax as parser.
But the problem is our test failes with this library, due to strange behaviour. perhaps bug? :)

As shown in picture, we're passing that HTML to the parser, but
1. Why table is empty? we didn't structured <table> tag like that. UL comes in table, but in your code that didn't happen. Not sure why you modify the input
2. Why there's a <head> tag insert by this library? I could see you have some attr for head, but can't you initialize it as None if there's no head in HTML?

<img width="1071" alt="Screenshot 2023-07-13 at 19 31 27" src="https://github.com/rushter/selectolax/assets/86913668/990681ce-7e42-4496-bff0-ea9be51d324b">
<img width="900" alt="Screenshot 2023-07-13 at 19 31 04" src="https://github.com/rushter/selectolax/assets/86913668/0686d635-5287-4ecd-b370-a0051cc9f4e1">

**Comment by rushter** [comment]
Can you post the original HTML snippet (as text)?

**Comment by rushter** [comment]
I don't see any problems here. It's not allowed to have ul tags inside table. If you open such HTML in Chrome, it most likely will be transformed in a similar way. That's how malformed HTML is handled by parsers.

**Comment by ManiMozaffar** [comment]
> I don't see any problems here (visually, looking at the screenshot). It's not allowed to have `ul` tags inside `table`. If you open such HTML in Chrome, it most likely will be transformed in a similar way. That's how malformed HTML is handled by parsers and browsers.

Hmm I understand what you're saying, but is there a way we can escape it?
I'm writing a library, called FastCrawler.
What we want to do is to offer a pydantic interface for data models. like

```
from fastcrawler import CssField, SelectoLaxProcessor, BaseModel

class Person(BaseModel):
    name: str = CssField(query="td:nth-child(1)::text" , processor=SelectoLaxProcessor)
    id: int = CssField(query="td:nth-child(2)::text" , processor=SelectoLaxProcessor)
    
class PersonTable(BaseModel):
    persons: list[Person] = CssField(query="table tr" , processor=SelectoLaxProcessor)
```

so I need to iterate over HTML elements, and parse them accordingly. I wouldn't except the string i'm giving is different than what real there is.

**Comment by rushter** [comment]
No, the parser works the same way as browsers, so it's not possible, unfortunately. Some old browsers won't even display part of this HTML.
