### ISSUE TITLE
Best way to handle content not found?

### ISSUE THREAD

**Issue by ThinksFast** [rushter/selectolax#99]
When web scraping, you have to deal with a lot of edge cases across websites.  What's the best way to handle a statement like this, where I'm trying to parse out the HREF value, but the canonical node isn't present in the HTML source.

`parser.css_first('link[rel="canonical"]').attributes['href'])`

I tried adding `default=dict(href=None)` to the `css_first` funct, but a dict won't chain with `attributes`.  Is there a graceful way to handle this, without using a bunch of if/else statements for every element like this?

**Comment by rushter** [comment]
You can just use `.attributes.get('href', None)`

**Comment by ThinksFast** [comment]
Hey, thanks for the reply.  So this solution works if the item has attributes (it exists in the DOM).  

If the item isn't in the DOM, then it throws exceptions.  And I don't see a way to handle this with fetching something that doesn't have attributes, like text.  

Side note:  for some reason, VSCode says it can't import `selectolax.lexbor`, despite the cell running in a python notebook.  So apologies if i'm missing something, intellisense isn't working and it's been difficult to inspect the `selectolax` code. 

But here's an example that better showcases the issues I'm facing:

```
from selectolax.lexbor import LexborHTMLParser, LexborNode

html = '<html><head><title>Title Text</title></head><body><p class="lead">Leading text</p><p class="main">Heres some article text</p></body></html>'
parser = LexborHTMLParser(html)

print(parser.css_first('title').text())     # Works since there's a title element

print(parser.css_first('link[rel="canonical"]').attributes.get('href', None))     # Throws an exception because `css_first` = None

print(parser.css_first('link[rel="canonical"]', default=dict(href="Not found")).attributes.get('href', None))     # Throws AttributeError: 'dict' object has no attribute 'attributes'

print(parser.css_first('.lead').text())     # Works because class exists

print(parser.css_first('.mainnn').text())     # Exception because class doesn't exist

print(parser.css_first('.mainnn').attributes)     # No Attributes to work with on a None object

print(parser.css_first('.mainnn', default='Default text').text())     # AttributeError: 'str' object has no attribute 'text'
```

**Comment by rushter** [comment]
You can make a dummy object and pass it to the default argument. 
But in general, it's better to have lots of checks so that you will know when something has changed in the HTML code.

**Comment by ThinksFast** [comment]
Thanks.  While this can be worked around as you suggested, I think it will add a lot of code and could get quite messy when parsing a lot of stuff.  My use case is doing broad crawls of URLs, pulling 30-100 different elements from each page.  When doing a broad crawl, the HTML has a lot of variance in quality.  Missing page titles, no headers, no images/text/etc.  And some pages are completely broken, I've actually found instances where there was no `<body>` tag.  lol

Anyway, I think your library is great, its soooo fast compared to other options out there.  But it might be more resilient if it safely returned None or Empty lists / iterables when no matches are found.  I think you'll see other parsing libraries implement this kind of behavior.  BS4 and Parsel, for example. 

Anyway, just my two cents as a user.  I'll try to work with your suggestion and see how it goes 🙂

**Comment by ThinksFast** [comment]
Hi @rushter, I'm digging up this old issue.  I am refactoring one of my parsers and decided to try using Selectolax.  

As you suggested, I implemented a dummy object to use as a default, which helps control for exceptions when an element is not found. But I am running into another issue where PyLance throws a type check error when I chain methods together.  This is caused by `css_first` possibly returning `None`... `(LexborNode | DefaultT@css_first | None)`.  

Since it's kind of related my issue above, I decided to post it here.  Below is some example code, and I'm including a screenshot of the error in VS Code.  I can suppress this with `# pyright: ignore`, but I'm literally using this method 50+ times in the code, so it's a lot of ignore's.  

Would it be better for `css_first` to always return a `LexborNode`, even if it's empty?

```
html = """
    <html lang="en">
        <head>
            <title>Selectolax Rocks</title>
        </head>
        <body>
            <h1>Page H1</h1>
            <p>This is a paragraph.</p>
        </body>
    </html>
    """

class dummy:
    attributes = {}
    @staticmethod
    def text():...

parser = LexborHTMLParser(html)
parser.css_first("h1", dummy).text()
```


<img width="1281" alt="image" src="https://github.com/user-attachments/assets/2f19a2f6-08ca-4b57-bf58-55aa0381887b">

**Comment by ThinksFast** [comment]
I get similar issues with `attributes` when I try to do something downstream with the parsed content.  For example:

```
images = [node.attributes for node in parser.css("img")]
alt_text = [i.get("alt") for i in images if i.get('alt')]
[i for i in alt_text if i.startswith('Photo')]
```

Throws a type-checking error on `.startswith()` because `attributes` returns `dict[str, str | None]`

<img width="612" alt="image" src="https://github.com/user-attachments/assets/780d4040-9fec-4ffb-9489-fe93263fa5b5">
